profile:
  default: ignore
project:
  type: website
  # # https://github.com/chrisvoncsefalvay/chrisvoncsefalvay.github.io/blob/main/_quarto.yml
  # # https://quarto.org/docs/projects/scripts.html#pre-and-post-render
  pre-render:
    # Start by deleting temporary files
    - ./quarto_scripts/python/delete_util.py "posts/**/*.render.ipynb"
    - ./quarto_scripts/python/delete_util.py "_quarto-ignore.yml"
    # Delete ignored files for a clean build
    - git clean -Xdf posts/
    # Delete empty directories
    - find posts/ -type d -empty -delete
    # # Delete old drafts' file
    # - rm drafts.txt
    # Prepare repository for rendering
    - ./quarto_scripts/python/ignore_util.py "_quarto-ignore.yml" "posts/**/*[!render].ipynb"
    - ./quarto_scripts/python/copy_util.py "posts/**/*[!render].ipynb" "{name}.render.{ext}"
    - ./quarto_scripts/python/pre_render_util.py "posts/**/*.render.ipynb" "./quarto_scripts/python/add_metadata.py" "output-file=index"
    # https://github.com/quarto-dev/quarto-cli/issues/10841 - Quarto deletes the original index.ipynb file 
    # when rendering a different notebook (index.render.ipynb) with output-file: index, despite the original 
    # file being explicitly ignored in the project configuration. #10841
    - ./quarto_scripts/python/pre_render_util.py "posts/**/*.render.ipynb" "./quarto_scripts/python/add_metadata.py" "format.ipynb.output-file=index.output"
    - ./quarto_scripts/python/pre_render_util.py "posts/**/*.render.ipynb" "./quarto_scripts/python/pluck_metadata_filter.py"
    - ./quarto_scripts/python/pre_render_util.py "posts/**/*.render.ipynb" "./quarto_scripts/python/markdown_code_options.py"
  render:
    - "**/*.qmd"
    - "**/*.ipynb"
  post-render:
    # Finish by deleting temporary files
    - ./quarto_scripts/python/delete_util.py "posts/**/*.render.ipynb"
    - ./quarto_scripts/python/delete_util.py "_quarto-ignore.yml"
    # Delete ignored files for a clean build
    - git clean -Xdf posts/
    # Delete empty directories
    - find posts/ -type d -empty -delete
website:
  title: "ToKnow.ai"
  google-analytics: 'G-4R9DMKF8S7'
  favicon: "images/logo.png"
  image: "images/logo.png"
  open-graph: true
  twitter-card: 
    site: "@ToKnow_ai"
  site-url: https://toknow.ai
  description: "ToKnow.ai aims to extract knowledge from information in order to generate valuable insights and intelligence."
  navbar:
    logo: "images/logo-white.png"
    collapse-below: "md"
    left:
      - href: index.qmd
        text: Posts
      - href: apps.qmd
        text: Apps
      - about.qmd
    right:
      - icon: github
        href: https://github.com/ToKnow-ai
        aria-label: Github - ToKnow.ai
      - icon: twitter
        href: https://twitter.com/ToKnow_ai
        aria-label: Twitter - ToKnow.ai
      - icon: rss
        href: index.xml
        aria-label: ToKnow.ai RSS
  page-footer:
    border: true
    background: dark
    center: 
      - "Copyright © {{< year >}}, ToKnow.ai"
      - text: "Terms of Service"
        href: terms-of-service.qmd
      - text: "License"
        href: LICENSE
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: _styles.css
    link-external-newwindow: true
execute:
  freeze: auto
  cache: false
shortcodes:
  - quarto_scripts/lua/year.lua
  - quarto_scripts/lua/bash.lua
  - quarto_scripts/lua/pagepath.lua
  - quarto_scripts/lua/iframe.lua



