---
title: Terms of Service and Privacy Notice
toc: true
toc-title: Table of Contents
---

### Data and Analysis

The data used for analysis on ToKnow.ai belongs to their respective owners, who retain all rights over it. This data may have been crawled from publicly available sources or obtained through other means. In cases where data is crawled from public websites, ToKnow.ai will comply with the respective website's Terms of Use and applicable copyright laws, including fair use/dealing purposes such as research, private study, criticism, review, or reporting current events. ToKnow.ai may backup this data to ensure perpetual access. We strive to use reliable sources and implement quality control measures to ensure the best possible information. However, ToKnow.ai does not guarantee the accuracy or completeness of the data or analysis.
ToKnow.ai may publish cybersecurity information about vulnerabilities, exploits, or security flaws for educational and research purposes.

### Intended Use

The analysis, conclusions, and information provided on ToKnow.ai represent the views and interpretations of the respective authors and researchers involved; and are intended as informational resources only. The information should not be construed as financial, legal or other professional advice, recommendations, solicitations, or any other call to action. Any disclosed vulnerabilities are intended to promote responsible disclosure practices and raise awareness within the cybersecurity community. ToKnow.ai does not condone or encourage the unauthorized or illegal use of this information for malicious purposes or activities that may cause harm or damage to individuals, organizations, or systems.

### User Responsibilities

It is the responsibility of the user to evaluate and consider any conclusions from the analysis, consult with professional advisors if needed, and make their own informed decisions. ToKnow.ai cannot be held liable for any decisions or actions taken based on the information provided, including any misuse or unlawful application of cybersecurity-related information. Any misuse or unlawful application of the information contained on ToKnow.ai is strictly prohibited and may be subject to legal consequences. Readers are advised to exercise caution and seek professional guidance before attempting to replicate or implement any techniques or methodologies discussed.

### Limitations of Liability

By using ToKnow.ai, you agree that the information is provided "as is" without any warranties of any kind. Your use of ToKnow.ai is at your own risk. Links to external sources are provided solely for convenience and does not imply endorsement of the materials on those sources. ToKnow.ai does not accept liability arising directly or indirectly from the accuracy, content, or defects of the linked sources.
ToKnow.ai shall not be held liable for any direct, indirect, incidental, or consequential damages arising from the use or misuse of the information provided.

### Privacy Practices

ToKnow.ai collects and analyzes data as described above. Any personal information collected as part of the data will be processed in compliance with applicable data protection laws.

### Modification of Terms

These Terms of Service and Privacy Notice may be updated from time to time. Your continued use of ToKnow.ai constitutes acceptance of the updated terms.

Last Modified on {{< bash "git log -1 --format=%cs terms-of-service.qmd" >}}