on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          # Create Token at - https://github.com/settings/tokens
          # Add the token to - https://github.com/ToKnow-ai/ToKnow-ai.github.io/settings/secrets/actions (Repository secrets)
          # https://github.com/actions/checkout/issues/287#issuecomment-780483104
          # https://github.com/marketplace/actions/clone-github-repo-action#for-a-private-repository
          token: ${{ secrets.GH_PAT }}
      
      - name: Reset gh-pages branch
        run: |
          #!/bin/bash

          CURRENT_BRANCH=`git symbolic-ref --short HEAD`
          TEMP_BRANCH="temp-branch-$(date +%s)"
          ORIGIN_BRANCH='gh-pages'
          echo "TEMP_BRANCH='$TEMP_BRANCH'"
          git switch --orphan $TEMP_BRANCH
          git config user.name 'Github Action' 
          git config user.email 'ask@toknow.ai'
          git show $CURRENT_BRANCH:CNAME > CNAME
          git show $CURRENT_BRANCH:deployment-in-progress.html > index.html
          git show $CURRENT_BRANCH:deployment-in-progress.html > 404.html
          echo "Pages deployed on - $(date)" > README.md
          git add CNAME index.html 404.html README.md
          git commit -m "Pages deployed on - $(date)"
          git push origin $TEMP_BRANCH:$ORIGIN_BRANCH --force
          git checkout $CURRENT_BRANCH

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          tinytex: true # https://github.com/quarto-dev/quarto-cli/discussions/3620#discussioncomment-4355980

      - name: Install Python packages
        run: pip install -r quarto.requirements.txt

      - name: Install rsvg-convert # Could not convert a SVG to a PDF for output. Please ensure that rsvg-convert is available on the path.
        run: sudo apt-get install -y librsvg2-dev

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}