on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Recreate gh-pages branch
        run: |
          #!/bin/bash

          CURRENT_BRANCH=`git symbolic-ref --short HEAD`
          BRANCH='gh-pages'
          if git ls-remote --exit-code --heads origin $BRANCH >/dev/null; then
            git push origin --delete $BRANCH  # Push deletion to remote repository
            echo "Git branch '$BRANCH' deleted in the remote repository"
          else
            echo "Git branch '$BRANCH' does not exist in the remote repository"
          fi
          git switch --orphan $BRANCH
          git config user.name 'Github Action' 
          git config user.email 'ask@toknow.ai'
          date +%s > report.txt
          git add report.txt
          git commit -m "Initial commit"
          git push --set-upstream origin $BRANCH
          git checkout $CURRENT_BRANCH

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          tinytex: true # https://github.com/quarto-dev/quarto-cli/discussions/3620#discussioncomment-4355980

      - name: Install Python packages
        run: pip install -r requirements.txt

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}